In [3]:
from numpy import array
from numpy import diag
from numpy import dot
from scipy.linalg import svd

In [4]:
# define a matrix that needs to be decomposed thru SVD
A = array([[2, 0, 1], [1, 2, 2]])
print(A)

[[2 0 1]
 [1 2 2]]


In [14]:
# applying Singular-value decomposition
U, s, VT = svd(A)

In [15]:
print(U)

[[ 0.52573111 -0.85065081]
 [ 0.85065081  0.52573111]]


In [16]:
print(s)

[3.38705417 1.5899258 ]


In [17]:
print(VT)

[[ 0.56158329  0.50229537  0.65751317]
 [-0.73938702  0.66132786  0.12630238]
 [-0.37139068 -0.55708601  0.74278135]]


In [18]:
# create n x n Sigma matrix
Sigma = diag(s)

In [19]:
print(Sigma)

[[3.38705417 0.        ]
 [0.         1.5899258 ]]


In [20]:
# reconstruct the matrix from u,s,vt
B = U.dot(Sigma.dot(A))
print(B)

[[ 2.20888785 -2.70494333 -0.92426358]
 [ 6.59827419  1.67174692  4.55294728]]
